package login;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.coobird.thumbnailator.Thumbnails;
import org.olap4j.impl.Base64;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vik
 */
public class ClientInformation extends javax.swing.JFrame {
    public Connection con;
    public PreparedStatement ps;
    ResultSet rs;
    ModelLogin cl = new ModelLogin();
    String filename = null;
    byte[] person_image = null;
    String imgpath=null;
    Model m = new Model();
    Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Vik\\Desktop\\ISE FINAL PROJECT'\\Capture.PNG");
    InputStream img;
    /**
     * Creates new form ClientInformation
     */
    public ClientInformation() {
        initComponents();
        con = ModelLogin.getConnection();
        this.setIconImage(ic);
        this.setLocationRelativeTo(null);
        
    }
    
     public static boolean validateEmail(String email) {                 
       boolean status=false;    
       String EMAIL_PATTERN = 
  "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
  + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
       Pattern pattern = Pattern.compile(EMAIL_PATTERN);
       Matcher matcher=pattern.matcher(email);
       if(matcher.matches())
       {
           status=true;
       }
       else{
           status=false;
       }
           return status;
            
    }
     
     
//    public ImageIcon ResizeImage(String ImagePath,byte[] pic)
//     {
//       ImageIcon Myimage=null;
//       if(ImagePath != null)
//       {
//           Myimage = new ImageIcon(ImagePath);
//       }
//       else
//       {
//           Myimage = new ImageIcon(pic);
//       }
//       Image img = Myimage.getImage();
//       Image newImg = img.getScaledInstance(CImage_label.getWidth(),CImage_label.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon image = new ImageIcon(newImg);
//       return image;
//     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Client_Ntn_Number = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Client_Name = new javax.swing.JTextField();
        Client_Email = new javax.swing.JTextField();
        Client_Company_Name = new javax.swing.JTextField();
        Client_Contact = new javax.swing.JFormattedTextField();
        Client_Address = new javax.swing.JTextField();
        Client_Image = new javax.swing.JLabel();
        Client_Image1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, -10, 300, 90);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLIENT INFORMATION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 40, 250, 50);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton1.setText("ATTACH IMAGE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 310, 220, 20);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("VIEW");
        jButton2.setActionCommand("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 560, 140, 20);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NTN NUMBER");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 520, 150, 20);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EMAIL");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 430, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADDRESS");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 460, 150, 20);

        Client_Ntn_Number.setBackground(new java.awt.Color(51, 51, 51));
        Client_Ntn_Number.setForeground(new java.awt.Color(255, 255, 255));
        try {
            Client_Ntn_Number.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Client_Ntn_Number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Client_Ntn_Number);
        Client_Ntn_Number.setBounds(230, 520, 370, 20);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("COMPANY NAME");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 490, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("NAME");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 370, 150, 20);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CONTACT");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 400, 150, 20);

        Client_Name.setBackground(new java.awt.Color(51, 51, 51));
        Client_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Name);
        Client_Name.setBounds(230, 370, 370, 20);

        Client_Email.setBackground(new java.awt.Color(51, 51, 51));
        Client_Email.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Email.setForeground(new java.awt.Color(255, 255, 255));
        Client_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_EmailActionPerformed(evt);
            }
        });
        Client_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Client_EmailKeyTyped(evt);
            }
        });
        jPanel1.add(Client_Email);
        Client_Email.setBounds(230, 430, 370, 20);

        Client_Company_Name.setBackground(new java.awt.Color(51, 51, 51));
        Client_Company_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Company_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Company_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Company_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Company_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_Company_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Company_Name);
        Client_Company_Name.setBounds(230, 490, 370, 20);

        Client_Contact.setBackground(new java.awt.Color(51, 51, 51));
        Client_Contact.setForeground(new java.awt.Color(255, 255, 255));
        try {
            Client_Contact.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Client_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_ContactActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Contact);
        Client_Contact.setBounds(230, 400, 370, 20);

        Client_Address.setBackground(new java.awt.Color(51, 51, 51));
        Client_Address.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Address.setForeground(new java.awt.Color(255, 255, 255));
        Client_Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Address);
        Client_Address.setBounds(230, 460, 370, 20);

        Client_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(Client_Image);
        Client_Image.setBounds(220, 90, 220, 210);

        Client_Image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(Client_Image1);
        Client_Image1.setBounds(220, 90, 220, 210);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setText("SAVE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(430, 560, 140, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(580, 0, 30, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 610, 620);

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(610, 440, 80, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//       JFileChooser chooser = new JFileChooser();
////        chooser.setCurrentDirectory(new File(System.getProperty("User.home")));
//        int result = chooser.showOpenDialog(null);
//        
//         if(result==JFileChooser.CANCEL_OPTION){
//                    chooser.disable();
//                    JOptionPane.showMessageDialog(null, "No Image Selected");
//           filename = null;
//                    CImage_label.setIcon(null);
//                    
//         }
//         
//         else{
//         File f = chooser.getSelectedFile();
//         String sf = f.getAbsolutePath();
//         CImage_label.setIcon((ResizeImage(sf,null)));
////        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(CImage.getWidth(), CImage.getHeight(), Image.SCALE_DEFAULT));
////        CImage.setIcon(imageIcon);
////        
//        imgpath = sf; 
//
//      
//                                  
//      try {
//
//            File image = new File(filename);
//             FileInputStream fis = new FileInputStream (image);
//        }
//        catch(Exception e){
//            
//       
//        }
//         }      
// 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
       
    JFileChooser chooser = new JFileChooser();
        int result =chooser.showOpenDialog(null);
        
         if(result==JFileChooser.CANCEL_OPTION){
                    chooser.disable();
                    filename = null;
                    Client_Image.setIcon(null);
         }
         
         else{
         File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
     
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(Client_Image.getWidth(), Client_Image.getHeight(), Image.SCALE_DEFAULT));
        Client_Image.setIcon(imageIcon);
        
                                  
      try {
            File image = new File(filename);
            BufferedImage bi = ImageIO.read(image);
            BufferedImage thumbnail = Thumbnails.of(bi).size(300, 300).asBufferedImage();
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            ImageIO.write(thumbnail, "jpeg", os);
            ByteArrayInputStream is = new ByteArrayInputStream(os.toByteArray());
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            
            byte[] buff = new byte[1024];
            try 
            {
            for (int readNum; (readNum=fis.read(buff))!= -1;) 
                {
                 bos.write(buff, 0,readNum);
                 System.out.println("Read "+readNum+" bytes ,");
                }
          } catch (Exception e) 
          {
               JOptionPane.showMessageDialog(null, e);
          }
            person_image = bos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please Select an Image"+e);
       
        }    }   
         
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     CLIENTVIEW cv= new CLIENTVIEW();
     cv.setVisible(true);
     cv.setLocationRelativeTo(null);
     setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Client_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_NameActionPerformed

    private void Client_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_EmailActionPerformed
//        boolean status= validateEmail(Client_Email.getText());
//       if(status){
//           jLabel7.setText("Email Valid");
//       }else{
//           jLabel7.setText("Not Valid Email");
//       }
    }//GEN-LAST:event_Client_EmailActionPerformed

    private void Client_Company_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_Company_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_Company_NameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          
                
                      boolean status= validateEmail(Client_Email.getText());
//       if(status){
//           System.out.println("Email Valid");
//       }else{
//           JOptionPane.showMessageDialog(null,"Invalid Email");
//       }
       if(Client_Ntn_Number.getText().equals("") || Client_Email.getText().equals("") || Client_Contact.getText().equals("") || 
           Client_Address.getText().equals("") || Client_Company_Name.getText().equals("") 
           || Client_Name.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "Please Fill All The Details");
           
        }
                else{
              if (status != true) {
                       JOptionPane.showMessageDialog(null,"Invalid Email");
           } else {
           
             String Name = Client_Name.getText();
             String contact = Client_Contact.getText();
             String email = Client_Email.getText();
             String address =  Client_Address.getText();
             String companyname = Client_Company_Name.getText();
             String ntnno = Client_Ntn_Number.getText();
             
        try {
            ps=con.prepareStatement("INSERT INTO `client`(`name`, `startdate`, `enddate`, `contact`, `email`, `address`, `status`, `companyname`, `ntnno`, `image`) VALUES (?,?,?,?,?,?,?,?,?,?)");
           
             
             
             if(imgpath != null){ 
            img = new FileInputStream(new File(imgpath));
            }
           
            ps.setString(1, Name);
            ps.setString(2, null);
            ps.setString(3, null);
            ps.setString(4, contact);
            ps.setString(5, email);
            ps.setString(6, address);
            ps.setString(7, null);
            ps.setString(8, companyname);
            ps.setString(9, ntnno);
           
            ps.setBytes(10, person_image);
                  ps.execute();
            JOptionPane.showMessageDialog(null, "values addeed successfully ");
            Client_Ntn_Number.setText("");
            Client_Email.setText("");
            Client_Contact.setText(""); 
            Client_Address.setText("");
            Client_Company_Name.setText(""); 
            Client_Name.setText("");








//            String dirName="C:\\";
//		ByteArrayOutputStream baos=new ByteArrayOutputStream(1000);
//		BufferedImage img=ImageIO.read(new File(dirName,"rose.jpg"));
//		ImageIO.write(img, "jpg", baos);
//		baos.flush();
// 
//		String base64String=Base64.encodeBytes(baos.toByteArray());
//		baos.close();
// 
//		byte[] bytearray = Base64.decode(base64String);
// 
//		BufferedImage imag=ImageIO.read(new ByteArrayInputStream(bytearray));
//		ImageIO.write(imag, "jpg", new File(dirName,"snap.jpg"));
	
// if(ps.executeUpdate() == 1)
//            {
//               JOptionPane.showMessageDialog(this, "Image Inserted");
//             }
        }
catch (Exception e) {
            JOptionPane.showMessageDialog(this, "EXCEPTION OCCUR "+e);
             }
        
                }
       }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     hp.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Client_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_AddressActionPerformed

    private void Client_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Client_EmailKeyTyped
        
    }//GEN-LAST:event_Client_EmailKeyTyped

    private void Client_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_ContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Client_Address;
    private javax.swing.JTextField Client_Company_Name;
    private javax.swing.JFormattedTextField Client_Contact;
    private javax.swing.JTextField Client_Email;
    private javax.swing.JLabel Client_Image;
    private javax.swing.JLabel Client_Image1;
    private javax.swing.JTextField Client_Name;
    private javax.swing.JFormattedTextField Client_Ntn_Number;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
