package login;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vik
 */
public class CLIENTVIEW extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
   Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\apex\\Desktop\\LATEST ISE PROJECT\\Capture.PNG");
     DefaultTableModel model;
    String filename = null;
    byte[] person_image = null;
    String imgpath=null;
    InputStream img;
    /**
     * Creates new form TENDER
     */
    public CLIENTVIEW() {
        initComponents();
     this.setIconImage(ic);
     this.setLocationRelativeTo(null);
     fillClientjTable(jTable1,"");
        System.out.println(""+img);
  
//    fillClientjTable(jTable1,jTextField_Val_Find.getText());
//  
        
    }
     public void fillClientjTable(JTable table,String valueToSearch)
            {
              Connection con = ModelLogin.getConnection();
         
        try { 
            PreparedStatement ps=con.prepareStatement("SELECT `clientid`, `name`, `contact`, `email`, `address`, `companyname`, `ntnno` FROM `client` WHERE CONCAT(`clientid`, `name`, `contact`, `email`, `address`, `companyname`, `ntnno`)LIKE ?");
            ps.setString(1, "%"+valueToSearch+"%");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            
            Object[] row;
            
            while(rs.next())
            {
               row = new Object[7];
               row[0] = rs.getInt(1);
               row[1] = rs.getString(2);
               row[2] = rs.getString(3);
               row[3] = rs.getString(4);
               row[4] = rs.getString(5);
               row[5] = rs.getString(6);
               row[6] = rs.getString(7);
               
               model.addRow(row);
               
            }
            
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Client jTable Query Not Executed Successfully ");
        }}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        Client_Name = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField_Val_Find = new javax.swing.JTextField();
        Client_Image = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Client_Id = new javax.swing.JTextField();
        Client_Contact = new javax.swing.JTextField();
        Client_Email = new javax.swing.JTextField();
        Client_Address = new javax.swing.JTextField();
        Client_Company_Name = new javax.swing.JTextField();
        Client_Ntn_Number = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CDate = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextField_STD_ID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(153, 153, 153));
        jButton12.setText("     ATTACH IMAGE");
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setText("SAVE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 10, 300, 60);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1020, 380, 73, 23);

        jButton14.setText("Delete");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(1110, 380, 73, 23);

        Client_Name.setBackground(new java.awt.Color(51, 51, 51));
        Client_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Name);
        Client_Name.setBounds(500, 210, 370, 20);

        jButton19.setBackground(new java.awt.Color(102, 102, 102));
        jButton19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton19.setText("ATTACH IMAGE");
        jButton19.setBorder(null);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(890, 380, 120, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Enter The Value To Search:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(540, 100, 217, 22);

        jTextField_Val_Find.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_Val_Find.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jTextField_Val_Find.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Val_Find.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Val_Find.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField_Val_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Val_FindActionPerformed(evt);
            }
        });
        jTextField_Val_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Val_FindKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_Val_Find);
        jTextField_Val_Find.setBounds(760, 100, 370, 20);

        Client_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Image);
        Client_Image.setBounds(920, 170, 220, 200);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("NAME");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(310, 210, 150, 20);

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "CONTACT", "EMAIL", "ADDRESS", "COMAPNY NAME", "NTN NUMBER"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 450, 810, 400);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("NTN NUMBER");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(310, 410, 150, 20);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("EMAIL");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(310, 290, 150, 20);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADDRESS");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(310, 330, 150, 20);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("COMPANY NAME");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(310, 370, 150, 20);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ID");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(310, 170, 150, 20);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("CONTACT");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(310, 250, 150, 20);

        Client_Id.setBackground(new java.awt.Color(51, 51, 51));
        Client_Id.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Id.setForeground(new java.awt.Color(255, 255, 255));
        Client_Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Id);
        Client_Id.setBounds(500, 170, 370, 20);

        Client_Contact.setBackground(new java.awt.Color(51, 51, 51));
        Client_Contact.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Contact.setForeground(new java.awt.Color(255, 255, 255));
        Client_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_ContactActionPerformed(evt);
            }
        });
        Client_Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Client_ContactKeyTyped(evt);
            }
        });
        jPanel1.add(Client_Contact);
        Client_Contact.setBounds(500, 250, 370, 20);

        Client_Email.setBackground(new java.awt.Color(51, 51, 51));
        Client_Email.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Email.setForeground(new java.awt.Color(255, 255, 255));
        Client_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Email);
        Client_Email.setBounds(500, 290, 370, 20);

        Client_Address.setBackground(new java.awt.Color(51, 51, 51));
        Client_Address.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Address.setForeground(new java.awt.Color(255, 255, 255));
        Client_Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Address);
        Client_Address.setBounds(500, 330, 370, 20);

        Client_Company_Name.setBackground(new java.awt.Color(51, 51, 51));
        Client_Company_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Company_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Company_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Company_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Company_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_Company_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Company_Name);
        Client_Company_Name.setBounds(500, 370, 370, 20);

        Client_Ntn_Number.setBackground(new java.awt.Color(51, 51, 51));
        Client_Ntn_Number.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Ntn_Number.setForeground(new java.awt.Color(255, 255, 255));
        Client_Ntn_Number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Client_Ntn_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Client_Ntn_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_Ntn_NumberActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Ntn_Number);
        Client_Ntn_Number.setBounds(500, 410, 370, 20);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 153, 153));
        jButton10.setText("       QUOTATION");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(60, 250, 160, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("     GENERATE BILL");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(60, 330, 160, 30);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 153, 153));
        jButton7.setText("     CLIENT ORDER");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 370, 160, 30);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("CLIENT INFORMATION");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(60, 530, 160, 30);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 153, 153));
        jButton9.setText("     GET RATES");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(60, 290, 160, 30);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 153, 153));
        jButton11.setText("     TENDER");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(60, 210, 160, 30);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(153, 153, 153));
        jButton13.setText("PAY THE PAYMENT");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(60, 450, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/deal (4).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 270, 180);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CLIENT VIEW");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 60, 120, 20);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 153, 153));
        jButton15.setText("GENERATE PAYMENT");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(60, 490, 160, 30);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(153, 153, 153));
        jButton16.setText("VENDOR INFORMATION");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(60, 570, 160, 30);

        jButton20.setText("GENERATE CLIENTS REPORT");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(890, 420, 250, 23);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(153, 153, 153));
        jButton17.setText("PRDOUCT INFORMATION");
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(60, 610, 160, 30);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(153, 153, 153));
        jButton18.setText("     ISSUE MATERIAL");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(60, 410, 160, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1190, 10, 30, 30);

        CDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(CDate);
        CDate.setBounds(0, 0, 1230, 740);

        jComboBox3.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox3.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(510, 420, 150, 22);

        jComboBox2.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(510, 380, 150, 22);

        jComboBox5.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox5.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(510, 420, 150, 22);

        jComboBox6.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox6.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(510, 420, 150, 22);

        jComboBox7.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox7.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox7.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox7);
        jComboBox7.setBounds(510, 420, 150, 22);

        jComboBox8.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox8.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox8.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(510, 420, 150, 22);

        jTextField_STD_ID.setEditable(false);
        jTextField_STD_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_STD_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_STD_IDKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_STD_ID);
        jTextField_STD_ID.setBounds(0, 0, 6, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter The Value To Search:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 217, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Address:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 68, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Phone:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 55, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Sex:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 34, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Birth Date:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 85, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("First Name:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 90, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Id:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 23, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Last Name:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 89, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
       
            

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      ClientInformation c = new ClientInformation();
      c.setVisible(true);
      c.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField_STD_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_STD_IDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_STD_IDKeyTyped

    private void Client_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_IdActionPerformed

    private void Client_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_ContactActionPerformed

    private void Client_ContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Client_ContactKeyTyped

    }//GEN-LAST:event_Client_ContactKeyTyped

    private void Client_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_EmailActionPerformed

    private void Client_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_AddressActionPerformed

    private void Client_Company_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_Company_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_Company_NameActionPerformed

    private void Client_Ntn_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_Ntn_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_Ntn_NumberActionPerformed

    private void Client_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_NameActionPerformed
int rowIndex;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         model =(DefaultTableModel)jTable1.getModel();
        rowIndex = jTable1.getSelectedRow();
        Client_Id.setText(model.getValueAt(rowIndex, 0).toString());
        Client_Name.setText(model.getValueAt(rowIndex, 1).toString());
        Client_Contact.setText(model.getValueAt(rowIndex, 2).toString());
        Client_Email.setText(model.getValueAt(rowIndex, 3).toString());
        Client_Address.setText(model.getValueAt(rowIndex,4).toString());
        Client_Company_Name.setText(model.getValueAt(rowIndex,5).toString());
        Client_Ntn_Number.setText(model.getValueAt(rowIndex,6).toString());
        Connection con = ModelLogin.getConnection();
       Client_Id.setEditable(false);  
        try {
             ps=con.prepareStatement("SELECT `image` FROM `client` WHERE `clientid` =?");
             ps.setString(1,Client_Id.getText());
            rs=ps.executeQuery();
            while(rs.next())
            {
                byte [] img = rs.getBytes("image");
               ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(Client_Image.getWidth(), Client_Image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                Client_Image.setIcon(newImage);

                
     

        }
        }
        catch(Exception e){
                
                }
        
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_Val_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Val_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Val_FindActionPerformed

    private void jTextField_Val_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Val_FindKeyReleased
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"Id","Name","Contact","Email","Address","CompanyName","Ntnno"}));
        fillClientjTable(jTable1, jTextField_Val_Find.getText());
        
    }//GEN-LAST:event_jTextField_Val_FindKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
        if(Client_Ntn_Number.getText().equals("") || Client_Email.getText().equals("") || Client_Contact.getText().equals("") || 
           Client_Address.getText().equals("") || Client_Company_Name.getText().equals("") || Client_Id.getText().equals("")
           || Client_Name.getText().equals("") || Client_Image.getIcon().equals(null))
        {
           JOptionPane.showMessageDialog(null, "Please Fill All The Details");
           
        }
        else
        {
        Connection con = ModelLogin.getConnection();
    
    String id = Client_Id.getText();
    String name = Client_Name.getText();
    String contact = Client_Contact.getText();
    String email = Client_Email.getText();
    String address = Client_Address.getText();
    String companyname = Client_Company_Name.getText();
    String ntn = Client_Ntn_Number.getText();
      try 
            {
               
                ps = con.prepareStatement("UPDATE `Client` SET `name` = ?, `contact` = ?, `email` = ?, `address` = ?, `companyname` = ?, `ntnno` = ? , `image` = ? WHERE `clientid` = ? ");
                if(imgpath != null){ 
                        img = new FileInputStream(new File(imgpath));
                    } 
             
                ps.setString(1, name);
                ps.setString(2, contact);
                ps.setString(3, email);
                ps.setString(4, address);
                ps.setString(5, companyname);
                ps.setString(6, ntn);
                 ps.setBlob(7, img);
                 ps.setString(8, id);
                ps.executeUpdate();
                
                
                     JOptionPane.showMessageDialog(null, "Client Data Updated Successfully");
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Client Update Query Not Executed Successfully"+ex);
            } 
            
        fillClientjTable(jTable1,"");
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"Id","Name","Contact","Email","Address","Companyname","Ntno"}));
         fillClientjTable(jTable1, "");
          Client_Id.setText("");
          Client_Name.setText("");
          Client_Contact.setText("");
          Client_Email.setText("");
          Client_Company_Name.setText("");
          Client_Ntn_Number.setText("");
          Client_Address.setText("");
          Client_Image.setIcon(null);
          
                }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        if(Client_Ntn_Number.getText().equals("") || Client_Email.getText().equals("") || Client_Contact.getText().equals("") || 
           Client_Address.getText().equals("") || Client_Company_Name.getText().equals("") || Client_Id.getText().equals("")
           || Client_Name.getText().equals("") || Client_Image.getIcon().equals(null))
        {
           JOptionPane.showMessageDialog(null, "Please Fill All The Details");
           
        }
        
        else
        {
        Connection con = ModelLogin.getConnection();
    int yesOrNo = JOptionPane.showConfirmDialog(null,  "Are you sure you want to delete?" , "Delete Client",JOptionPane.OK_CANCEL_OPTION,0);
            
            if(yesOrNo == JOptionPane.OK_OPTION)
            {       
 try 
            {
                ps = con.prepareStatement("DELETE FROM `client` WHERE `clientid` = ?");
                ps.setString(1, Client_Id.getText()); 
                if(ps.executeUpdate()>0)
                {
                     JOptionPane.showMessageDialog(null, "Client Data Deleted Successfully");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Client Delete Query Not Executed Successfully");
            }}
        fillClientjTable(jTable1,"");
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"Id","Name","Contact","Email","Address","Companyname","Ntno"}));
         fillClientjTable(jTable1, "");
          Client_Id.setText("");
          Client_Name.setText("");
          Client_Contact.setText("");
          Client_Email.setText("");
          Client_Company_Name.setText("");
          Client_Ntn_Number.setText("");
          Client_Address.setText("");
          Client_Image.setIcon(null);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(CLIENTVIEW.this);

        if(result==JFileChooser.CANCEL_OPTION){
            chooser.disable();
            filename = null;
            Client_Image.setIcon(null);
        }

        else{
            File f = chooser.getSelectedFile();
            filename = f.getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(Client_Image.getWidth(), Client_Image.getHeight(), Image.SCALE_DEFAULT));
            Client_Image.setIcon(imageIcon);

            try {

                File image = new File(filename);
                img = new FileInputStream (image);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);

            }    }

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
          Connection con = ModelLogin.getConnection();
        try {
           String path="E:\\FISE PROJECT\\Tender Managment System Final\\LOGIN\\src\\login\\ClientsImage.jrxml";
           JasperReport jr = JasperCompileManager.compileReport(path);
           JasperPrint jp =JasperFillManager.fillReport(jr, null, con);
           JasperViewer.viewReport(jp,false);
           con.close();
       } catch (JRException ex) {
           Logger.getLogger(Quotation.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {        
            Logger.getLogger(CLIENTVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLIENTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLIENTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLIENTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLIENTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLIENTVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CDate;
    private javax.swing.JTextField Client_Address;
    private javax.swing.JTextField Client_Company_Name;
    private javax.swing.JTextField Client_Contact;
    private javax.swing.JTextField Client_Email;
    private javax.swing.JTextField Client_Id;
    private javax.swing.JLabel Client_Image;
    private javax.swing.JTextField Client_Name;
    private javax.swing.JTextField Client_Ntn_Number;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_STD_ID;
    private javax.swing.JTextField jTextField_Val_Find;
    // End of variables declaration//GEN-END:variables
}
