package login;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vik
 */
public class GENERATEBILLform extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Vik\\Desktop\\ISE FINAL PROJECT'\\Capture.PNG");
    int i =0;
    /**
     * Creates new form GENERATEBILLform
     */
    public GENERATEBILLform() {
        initComponents();
        ModelLogin cl = new ModelLogin();
        ModelGBill mgb = new ModelGBill();
        mgb.statusComboB(Vendor_Id);
        mgb.statusComboB1(Product_Name);

        mgb.statusComboB2(jComboBox12);
        this.setIconImage(ic);
        this.setLocationRelativeTo(null);

    }
    private ImageIcon format = null;
    //strin filename
    String filename = null;
    byte[] person_image = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Vendor_Name = new javax.swing.JLabel();
        Vendor_Image = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        Date = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        Market_Name = new javax.swing.JTextField();
        Bill_Receiver = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        Market_Address = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Product_Name = new javax.swing.JComboBox<>();
        Vendor_Id = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(153, 153, 153));
        jButton12.setText("     ATTACH IMAGE");
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 0, 300, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("     ISSUE MATERIAL");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(60, 420, 160, 30);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 153, 153));
        jButton7.setText("     CLIENT ORDER");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 380, 160, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("     GENERATE BILL");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(60, 340, 160, 30);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 153, 153));
        jButton9.setText("     GET RATES");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(60, 300, 160, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 153, 153));
        jButton10.setText("       QUOTATION");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(60, 260, 160, 30);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 153, 153));
        jButton11.setText("     TENDER");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(60, 220, 160, 30);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(153, 153, 153));
        jButton13.setText("GENERATE PAYMENT");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(60, 500, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/deal (4).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 270, 180);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GENERATE BILL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 50, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("     GENERATE BILL");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 280, 760, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STATUS");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(690, 320, 130, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(" MARKET NAME");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 320, 130, 20);

        Vendor_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Vendor_Name.setForeground(new java.awt.Color(255, 255, 255));
        Vendor_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vendor_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Vendor_Name);
        Vendor_Name.setBounds(510, 140, 150, 20);

        Vendor_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Vendor_Image);
        Vendor_Image.setBounds(680, 110, 190, 160);

        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("M/S");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel32);
        jLabel32.setBounds(340, 350, 130, 20);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 153, 153));
        jButton15.setText("PAY THE PAYMENT");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(60, 460, 160, 30);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("     GENERATE BILL LINE ITEM");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(310, 440, 760, 30);

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("     VENDOR INFORMATION");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 70, 760, 30);

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("NAME");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(340, 140, 150, 20);

        status.setBackground(new java.awt.Color(153, 153, 153));
        status.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(153, 153, 153));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Complete", "Incomplete" }));
        status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        status.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        status.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status);
        status.setBounds(860, 320, 150, 22);
        jPanel1.add(Date);
        Date.setBounds(860, 350, 150, 20);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DESCRIPTION", "UNIT PRICE", "QUANTITY", "TOTAL SUM"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBox12));
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 480, 690, 230);

        jLabel31.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText(" MARKET ADDRESS");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel31);
        jLabel31.setBounds(340, 380, 130, 20);

        Market_Name.setText("Enter the market name");
        Market_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Market_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Market_NameMouseClicked(evt);
            }
        });
        Market_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Market_NameActionPerformed(evt);
            }
        });
        Market_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Market_NameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Market_NameKeyTyped(evt);
            }
        });
        jPanel1.add(Market_Name);
        Market_Name.setBounds(510, 320, 150, 20);

        Bill_Receiver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bill_Receiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bill_ReceiverMouseClicked(evt);
            }
        });
        Bill_Receiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_ReceiverActionPerformed(evt);
            }
        });
        Bill_Receiver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Bill_ReceiverKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bill_ReceiverKeyTyped(evt);
            }
        });
        jPanel1.add(Bill_Receiver);
        Bill_Receiver.setBounds(510, 350, 150, 20);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setText("SAVE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(870, 410, 140, 20);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(153, 153, 153));
        jButton14.setText("CLIENT INFORMATION");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(60, 540, 160, 30);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(153, 153, 153));
        jButton16.setText("VENDOR INFORMATION");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(60, 580, 160, 30);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(153, 153, 153));
        jButton17.setText("PRDOUCT INFORMATION");
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(60, 620, 160, 30);

        Market_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Market_Address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Market_AddressMouseClicked(evt);
            }
        });
        Market_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Market_AddressActionPerformed(evt);
            }
        });
        Market_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Market_AddressKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Market_AddressKeyTyped(evt);
            }
        });
        jPanel1.add(Market_Address);
        Market_Address.setBounds(510, 380, 150, 20);

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("ID");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(340, 110, 150, 20);

        jLabel33.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText(" PRODUCT NAME");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel33);
        jLabel33.setBounds(690, 380, 130, 20);

        Product_Name.setBackground(new java.awt.Color(153, 153, 153));
        Product_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Product_Name.setForeground(new java.awt.Color(153, 153, 153));
        Product_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        Product_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Product_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Product_Name.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Product_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Product_Name);
        Product_Name.setBounds(860, 380, 150, 22);

        Vendor_Id.setBackground(new java.awt.Color(153, 153, 153));
        Vendor_Id.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Vendor_Id.setForeground(new java.awt.Color(153, 153, 153));
        Vendor_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Vendor_Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Vendor_Id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Vendor_Id.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Vendor_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendor_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Vendor_Id);
        Vendor_Id.setBounds(510, 110, 150, 22);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DATE");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(690, 350, 130, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1000, 0, 40, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 720);

        jComboBox12.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox12.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Number" }));
        jComboBox12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox12.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox12);
        jComboBox12.setBounds(510, 420, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void Vendor_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendor_IdActionPerformed
        // TODO add your handling code here:
        Connection con = ModelLogin.getConnection();

        try {
            ps = con.prepareStatement("SELECT `name`,image FROM `vendor` WHERE `vendorid` =?");
            ps.setString(1, (String) Vendor_Id.getSelectedItem());
            rs = ps.executeQuery();
            while (rs.next()) {
                Vendor_Name.setText(rs.getString("name"));
                byte[] img = rs.getBytes("image");
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(Vendor_Image.getWidth(), Vendor_Image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                Vendor_Image.setIcon(newImage);

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_Vendor_IdActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Quotation q = new Quotation();
        q.setVisible(true);
        q.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        GENERATEBILLform gb = new GENERATEBILLform();
        gb.setVisible(true);
        gb.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
        hp.setVisible(true);
        dispose();
        hp.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Market_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Market_NameMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_Market_NameMouseClicked

    private void Market_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Market_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Market_NameActionPerformed

    private void Market_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Market_NameKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_Market_NameKeyPressed

    private void Market_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Market_NameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Market_NameKeyTyped

    private void Bill_ReceiverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bill_ReceiverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_ReceiverMouseClicked

    private void Bill_ReceiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_ReceiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_ReceiverActionPerformed

    private void Bill_ReceiverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bill_ReceiverKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_ReceiverKeyPressed

    private void Bill_ReceiverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bill_ReceiverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_ReceiverKeyTyped

    private void Market_AddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Market_AddressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Market_AddressMouseClicked

    private void Market_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Market_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Market_AddressActionPerformed

    private void Market_AddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Market_AddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Market_AddressKeyPressed

    private void Market_AddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Market_AddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Market_AddressKeyTyped

    private void Product_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_NameActionPerformed
        // TODO add your handling code here:
        Connection con = ModelLogin.getConnection();
        int i = 0;
        try {
            ps = con.prepareStatement("SELECT * FROM get_rates WHERE description = '" + jComboBox12.getSelectedItem() + "'");
            // ps.setString(1,(String)jComboBox6.getSelectedItem());
            rs = ps.executeQuery();
            while (rs.next()) {
                String q = rs.getString("quantity");
                String d = rs.getString("price");

                System.out.println(q);
                jTable1.setValueAt(q, i, 1);
                jTable1.setValueAt(d, i, 2);

            }
            i++;
        } catch (Exception e) {

        }

    }//GEN-LAST:event_Product_NameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (Vendor_Id.getSelectedItem().equals("") || Vendor_Name.getText().equals("") || Vendor_Image.getText().equals("")
                || Market_Name.getText().equals("") || Market_Address.getText().equals("") || Bill_Receiver.getText().equals("")
                || status.getSelectedItem().equals("") || Date.getDate().equals("") || Product_Name.getSelectedItem().equals("")) {
             JOptionPane.showMessageDialog(null,"Please Fill All The Field");
        }
        else
        {
        Connection con = ModelLogin.getConnection();
        String marketname = Market_Name.getText();  
        String marketaddress = Market_Address.getText();
        String ms = Bill_Receiver.getText();
        String sta = status.getSelectedItem().toString();
        String pn = Product_Name.getSelectedItem().toString();

        java.util.Date date = Date.getDate();
        java.sql.Date Dat = new java.sql.Date(date.getTime());

        try {
            ps = con.prepareStatement("INSERT INTO `generate_bill`(vendorid,date , status,`marketname`,`marketaddress`, `productname`, `ms`) VALUES (?,?,?,?,?,?,?)");
            rs = ps.executeQuery();

            JOptionPane.showMessageDialog(null, "values addeed successfully ");

        } catch (Exception e) {

        }
        try {
            ps.setString(1, Vendor_Id.getSelectedItem().toString());
            ps.setDate(2, Dat);
            ps.setString(3, sta);
            ps.setString(4, marketname);
            ps.setString(5, marketaddress);
            ps.setString(6, pn);
            ps.setString(7, ms);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Has Been Saved Successfully");
           Vendor_Id.setSelectedIndex(0);
           Vendor_Name.setText("");
           Vendor_Image.setText("");
           Market_Name.setText("");
           Market_Address.setText("");
           Bill_Receiver.setText("");
            status.setSelectedIndex(0);
            Date.setDate(null);
            Product_Name.setSelectedIndex(0);
        
        
        
        
        
        
        
        
        
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
        Connection con = ModelLogin.getConnection();
        int i = 0;
        double tprice;

        try {
            ps = con.prepareStatement("SELECT quantity,price FROM `get_rates` WHERE `description` =?");
            ps.setString(1, (String) jComboBox12.getSelectedItem());
            rs = ps.executeQuery();

            while (rs.next()) {
                int p = rs.getInt("price");
                int q = rs.getInt("quantity");

                tprice = p * q;
                jTable1.setValueAt(q, i, 1);
                jTable1.setValueAt(p, i, 2);
                jTable1.setValueAt(tprice, i, 3);
                i++;

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        HOMEPAGE hp = new HOMEPAGE();
        hp.setVisible(true);
        hp.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        TENDER t = new TENDER();
        t.setVisible(true);
        t.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        GETRATES gr = new GETRATES();
        gr.setVisible(true);
        gr.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CLIENTORDER co = new CLIENTORDER();
        co.setVisible(true);
        co.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ISSUEMATERIAL im = new ISSUEMATERIAL();
        im.setVisible(true);
        im.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        ClientInformation ci = new ClientInformation();
        ci.setVisible(true);
        ci.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        VENDERINFORMATION vm = new VENDERINFORMATION();
        vm.setVisible(true);
        vm.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        generateQuotation pi = new generateQuotation();
        pi.setVisible(true);
        pi.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GENERATEBILLform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GENERATEBILLform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GENERATEBILLform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GENERATEBILLform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GENERATEBILLform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bill_Receiver;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTextField Market_Address;
    private javax.swing.JTextField Market_Name;
    private javax.swing.JComboBox<String> Product_Name;
    private javax.swing.JComboBox<String> Vendor_Id;
    private javax.swing.JLabel Vendor_Image;
    private javax.swing.JLabel Vendor_Name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
