package login;



import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vik
 */
public class ISSUEMATERIAL extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Vik\\Desktop\\ISE FINAL PROJECT'\\Capture.PNG");
    int i = 0;
    /**
     * Creates new form ISSUEMATERIAL
     */
    public ISSUEMATERIAL() {
        initComponents();
        this.setIconImage(ic);
        ModelLogin cl = new ModelLogin();
    ModelIMaterial m = new ModelIMaterial();
    m.statusComboI(Client_Id);
    m.statusComboI1(LPR_Number);;
    m.statusComboI2(desc);
       this.setIconImage(ic);
       this.setLocationRelativeTo(null);
        
    }
     private ImageIcon format =null;
    //strin filename
    String filename = null;
    byte[] person_image = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Client_Name = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Material_Receiver = new javax.swing.JTextField();
        LPO_Number = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        LPR_Number = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        Client_Id = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Client_Image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desc = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(153, 153, 153));
        jButton12.setText("     ATTACH IMAGE");
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 10, 300, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("     ISSUE MATERIAL");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(60, 420, 160, 30);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 153, 153));
        jButton7.setText("     CLIENT ORDER");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 380, 160, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("     GENERATE BILL");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(60, 340, 160, 30);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 153, 153));
        jButton9.setText("     GET RATES");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(60, 300, 160, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 153, 153));
        jButton10.setText("       QUOTATION");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(60, 260, 160, 30);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 153, 153));
        jButton11.setText("     TENDER");
        jButton11.setBorder(null);
        jPanel1.add(jButton11);
        jButton11.setBounds(60, 220, 160, 30);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(153, 153, 153));
        jButton13.setText("GENERATE PAYMENT");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(60, 500, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/deal (4).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 270, 180);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ISSUE MATERIAL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 60, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("     ISSUE MATERIAL");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 340, 760, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DATE");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(710, 380, 150, 20);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STATUS");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 440, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("M/s. ");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 380, 150, 20);

        Client_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Client_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Name);
        Client_Name.setBounds(510, 160, 150, 20);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("LPR NUMBER");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel20);
        jLabel20.setBounds(340, 410, 150, 20);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 153, 153));
        jButton15.setText("PAY THE PAYMENT");
        jButton15.setBorder(null);
        jPanel1.add(jButton15);
        jButton15.setBounds(60, 460, 160, 30);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("     ISSUE MATERIAL LINE ITEM");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(310, 470, 760, 30);

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("     CLIENT INFORMATION");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 90, 760, 30);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ID");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(340, 130, 150, 20);

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("LPO NUMBER");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(710, 410, 150, 20);

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("NAME");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(340, 160, 150, 20);

        Material_Receiver.setText(" Enter the name material receiver ");
        Material_Receiver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Material_Receiver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Material_ReceiverMouseClicked(evt);
            }
        });
        Material_Receiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Material_ReceiverActionPerformed(evt);
            }
        });
        Material_Receiver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Material_ReceiverKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Material_ReceiverKeyTyped(evt);
            }
        });
        jPanel1.add(Material_Receiver);
        Material_Receiver.setBounds(510, 380, 170, 20);

        LPO_Number.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        LPO_Number.setForeground(new java.awt.Color(255, 255, 255));
        LPO_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LPO_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(LPO_Number);
        LPO_Number.setBounds(880, 410, 170, 20);
        jPanel1.add(Date);
        Date.setBounds(880, 380, 170, 20);

        LPR_Number.setBackground(new java.awt.Color(153, 153, 153));
        LPR_Number.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        LPR_Number.setForeground(new java.awt.Color(153, 153, 153));
        LPR_Number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        LPR_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LPR_Number.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LPR_Number.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        LPR_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPR_NumberActionPerformed(evt);
            }
        });
        jPanel1.add(LPR_Number);
        LPR_Number.setBounds(510, 410, 170, 22);

        status.setBackground(new java.awt.Color(153, 153, 153));
        status.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(153, 153, 153));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "status", "Complete", "Incomplete" }));
        status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        status.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        status.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status);
        status.setBounds(510, 440, 170, 22);

        Client_Id.setBackground(new java.awt.Color(153, 153, 153));
        Client_Id.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Id.setForeground(new java.awt.Color(153, 153, 153));
        Client_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        Client_Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Client_Id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Client_Id.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Client_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Id);
        Client_Id.setBounds(510, 130, 150, 22);

        jComboBox5.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox5.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(510, 130, 150, 22);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DESCRIPTION", "DENO", "QUANTITY"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(desc));
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 530, 720, 110);

        Client_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Image);
        Client_Image.setBounds(830, 130, 210, 200);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1040, 10, 30, 30);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(153, 153, 153));
        jButton14.setText("SAVE");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(890, 440, 110, 20);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(153, 153, 153));
        jButton16.setText("VENDOR INFORMATION");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(60, 580, 160, 30);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(153, 153, 153));
        jButton17.setText("PRDOUCT INFORMATION");
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(60, 620, 160, 30);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(153, 153, 153));
        jButton18.setText("CLIENT INFORMATION");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(60, 540, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 750);

        desc.setBackground(new java.awt.Color(153, 153, 153));
        desc.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 153, 153));
        desc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "status" }));
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desc.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel1.add(desc);
        desc.setBounds(510, 440, 170, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void Client_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_IdActionPerformed
         Connection con = ModelLogin.getConnection();
         
        try {
             ps=con.prepareStatement("SELECT `name`,image FROM `client` WHERE `clientid` =?");
             ps.setString(1,(String)Client_Id.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            {
                Client_Name.setText(rs.getString("name"));
                   byte [] img = rs.getBytes("image");
               ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(Client_Image.getWidth(), Client_Image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                Client_Image.setIcon(newImage);
          
                
     

        }}
        catch(Exception e){
                
                }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_IdActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void LPR_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPR_NumberActionPerformed
        Connection con = ModelLogin.getConnection();

        try {
            ps=con.prepareStatement("SELECT lpono FROM `purchase_order` WHERE `lprno` =?");
            ps.setString(1,(String)LPR_Number.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            {
        
               
                
                LPO_Number.setText(rs.getString("lpono"));
 
               

            }}
            catch(Exception e){

            }
        // TODO add your handling code here:
    }//GEN-LAST:event_LPR_NumberActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          GENERATEBILLform gb = new GENERATEBILLform();
        gb.setVisible(true);
        gb.setLocationRelativeTo(null);
setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
  
        if (Client_Id.getSelectedItem().equals("") || Client_Name.getText().equals("") || Client_Image.getIcon().equals("")
      || Material_Receiver.getText().equals("") || Date.getDate().equals("") || LPR_Number.getSelectedItem().equals("")  || 
        LPO_Number.getText().equals("") || status.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null,"Please Fill All The Fields");
        }
        else
        {
        Connection con = ModelLogin.getConnection();
        String ms = Material_Receiver.getText();
        
                java.util.Date date=Date.getDate();
                java.sql.Date dat=new java.sql.Date(date.getTime());
              
        try {
                ps=con.prepareStatement("INSERT INTO `issue_material`(`lprno`, `date`, `status`, `ms`, `lpono`, `clientid`) VALUES  (?,?,?,?,?.?)");
             
            Statement st = con.createStatement();
            ps.setString(6,Client_Id.getSelectedItem().toString());
            ps.setString(1, LPR_Number.getSelectedItem().toString());
            ps.setString(3, status.getSelectedItem().toString());    
            ps.setDate(2,dat);
            ps.setString(4, ms);
            ps.setString(5,LPO_Number.getText());
            ps.execute();
           JOptionPane.showMessageDialog(this,"data Saved");
           Client_Id.setSelectedIndex(0);
           Client_Name.setText("");
           Client_Image.setIcon(null);
           Material_Receiver.setText(""); 
           Date.setDate(null);
            LPR_Number.setSelectedIndex(0);
            LPO_Number.setText("");
            status.setSelectedIndex(0);
                    
        } catch (Exception e) {
            System.out.println(e);
        }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     dispose();
     hp.setLocationRelativeTo(null);
setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here: 
        generateQuotation pi = new generateQuotation();
        pi.setVisible(true);
        pi.setLocationRelativeTo(null);
setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void Material_ReceiverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Material_ReceiverMouseClicked
        Material_Receiver.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_Material_ReceiverMouseClicked

    private void Material_ReceiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Material_ReceiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Material_ReceiverActionPerformed

    private void Material_ReceiverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Material_ReceiverKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_Material_ReceiverKeyPressed

    private void Material_ReceiverKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Material_ReceiverKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Material_ReceiverKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         GETRATES gr = new GETRATES();
        gr.setVisible(true);
        gr.setLocationRelativeTo(null);
setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         
        CLIENTORDER co = new CLIENTORDER();
        co.setVisible(true);
        co.setLocationRelativeTo(null);
setVisible(false);        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         ISSUEMATERIAL im = new ISSUEMATERIAL();
        im.setVisible(true);
        im.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         ClientInformation ci = new ClientInformation();
        ci.setVisible(true);
        ci.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
          VENDERINFORMATION vm = new VENDERINFORMATION();
        vm.setVisible(true);
        vm.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton13ActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
     Connection con = ModelLogin.getConnection();
        
        try {
            ps=con.prepareStatement("SELECT * FROM tender WHERE description = '"+desc.getSelectedItem()+"'");
           // ps.setString(1,(String)jComboBox6.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            {
             String q = rs.getString("quantity");
             String d = rs.getString("deno");
             jTable1.setValueAt(d, i, 1);
             jTable1.setValueAt(q, i, 2);
             i++;
            }}
            catch(Exception e){

            }
    }//GEN-LAST:event_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISSUEMATERIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISSUEMATERIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISSUEMATERIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISSUEMATERIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISSUEMATERIAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Client_Id;
    private javax.swing.JLabel Client_Image;
    private javax.swing.JLabel Client_Name;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JLabel LPO_Number;
    private javax.swing.JComboBox<String> LPR_Number;
    private javax.swing.JTextField Material_Receiver;
    private javax.swing.JComboBox<String> desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
