package login;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vik
 */
public class productinformation extends javax.swing.JFrame {
   Connection con;
    PreparedStatement ps;
    ResultSet rs;
 Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\apex\\Desktop\\LATEST ISE PROJECT\\Capture.PNG");
   String filename = null;
    InputStream img;
    byte[] person_image = null;
    String imgpath=null;
    int i =0;
    
        
       

    public productinformation() {
        initComponents();
        this.setIconImage(ic);
        this.setLocationRelativeTo(null);
         jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBox1));
         jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
         TableColumn col = jTable1.getColumnModel().getColumn(0);
         col.setPreferredWidth(350);
         col = jTable1.getColumnModel().getColumn(1);
         col.setPreferredWidth(50);
         col = jTable1.getColumnModel().getColumn(2);
         col.setPreferredWidth(150);
         Modelpinfo mpi = new Modelpinfo();
         mpi.statusComboI3(jComboBox1);
           
             
//             mpi.statusComboI4(product);
//             mpi.statusComboI5(product1);
//             mpi.statusComboI3(product2);
             jTable1.setShowGrid(true);
             jTable1.setGridColor(Color.yellow);
             jTable1.setSelectionBackground(Color.GREEN);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content oSf this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Label_ImageP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Product_Name = new javax.swing.JTextField();
        REPORT = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Quantity = new javax.swing.JTextField();
        Product_Image = new javax.swing.JLabel();
        Characteristics_Type_Name = new javax.swing.JTextField();
        pic = new javax.swing.JButton();
        Characteristics_Value = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        Unit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 20, 300, 60);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRODUCT DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 70, 250, 50);
        jPanel1.add(Label_ImageP);
        Label_ImageP.setBounds(570, 410, 190, 200);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText(" PRODUCT NAME");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 140, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(" UNIT OF MEASURE");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 180, 150, 20);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText(" QUANTITY");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 220, 150, 20);

        Product_Name.setBackground(new java.awt.Color(51, 51, 51));
        Product_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Product_Name.setForeground(new java.awt.Color(255, 255, 255));
        Product_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Product_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Product_Name.setOpaque(false);
        Product_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_NameActionPerformed(evt);
            }
        });
        Product_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Product_NameKeyTyped(evt);
            }
        });
        jPanel1.add(Product_Name);
        Product_Name.setBounds(220, 140, 190, 20);

        REPORT.setBackground(new java.awt.Color(102, 102, 102));
        REPORT.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        REPORT.setText("GENERATE PRODUCT REPORT");
        REPORT.setBorder(null);
        REPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTActionPerformed(evt);
            }
        });
        jPanel1.add(REPORT);
        REPORT.setBounds(40, 350, 200, 20);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText(" CT NAME");
        jLabel14.setToolTipText("CHARACTERISTICS TYPE NAME");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 260, 150, 20);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText(" CHARACTERISTICS VALUE");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 300, 150, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(730, 0, 30, 30);

        Quantity.setBackground(new java.awt.Color(51, 51, 51));
        Quantity.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Quantity.setForeground(new java.awt.Color(255, 255, 255));
        Quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Quantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Quantity.setOpaque(false);
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityKeyTyped(evt);
            }
        });
        jPanel1.add(Quantity);
        Quantity.setBounds(220, 220, 190, 20);

        Product_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(Product_Image);
        Product_Image.setBounds(440, 140, 220, 210);

        Characteristics_Type_Name.setBackground(new java.awt.Color(51, 51, 51));
        Characteristics_Type_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Characteristics_Type_Name.setForeground(new java.awt.Color(255, 255, 255));
        Characteristics_Type_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Characteristics_Type_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Characteristics_Type_Name.setOpaque(false);
        Characteristics_Type_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Characteristics_Type_NameActionPerformed(evt);
            }
        });
        Characteristics_Type_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Characteristics_Type_NameKeyTyped(evt);
            }
        });
        jPanel1.add(Characteristics_Type_Name);
        Characteristics_Type_Name.setBounds(220, 260, 190, 20);

        pic.setBackground(new java.awt.Color(102, 102, 102));
        pic.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        pic.setText("ATTACH IMAGE");
        pic.setBorder(null);
        pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picActionPerformed(evt);
            }
        });
        jPanel1.add(pic);
        pic.setBounds(440, 360, 220, 20);

        Characteristics_Value.setBackground(new java.awt.Color(51, 51, 51));
        Characteristics_Value.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Characteristics_Value.setForeground(new java.awt.Color(255, 255, 255));
        Characteristics_Value.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Characteristics_Value.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Characteristics_Value.setOpaque(false);
        Characteristics_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Characteristics_ValueActionPerformed(evt);
            }
        });
        jPanel1.add(Characteristics_Value);
        Characteristics_Value.setBounds(220, 300, 190, 20);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setText("SAVE");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(260, 350, 120, 20);

        Unit.setBackground(new java.awt.Color(51, 51, 51));
        Unit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Unit.setForeground(new java.awt.Color(255, 255, 255));
        Unit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Unit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Unit.setOpaque(false);
        Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitActionPerformed(evt);
            }
        });
        Unit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UnitKeyTyped(evt);
            }
        });
        jPanel1.add(Unit);
        Unit.setBounds(220, 180, 190, 20);

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ITEM NAME", "UNIT", "QUANTITY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBox1));
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 410, 540, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 750);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(690, 40, 54, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(580, 40, 56, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Product_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_NameActionPerformed

    private void REPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTActionPerformed
       
              Connection con = ModelLogin.getConnection();
        try {
           String path="E:\\FISE PROJECT\\Tender Managment System Final\\LOGIN\\src\\login\\Products.jrxml";
           JasperReport jr = JasperCompileManager.compileReport(path);
           JasperPrint jp =JasperFillManager.fillReport(jr, null, con);
           JasperViewer.viewReport(jp,false);
           con.close();
       } catch (JRException ex) {
           Logger.getLogger(Quotation.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {        
            Logger.getLogger(CLIENTVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_REPORTActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     dispose();
     hp.setLocationRelativeTo(null);
setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void Characteristics_Type_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Characteristics_Type_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Characteristics_Type_NameActionPerformed

    private void Characteristics_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Characteristics_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Characteristics_ValueActionPerformed

    private void UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnitActionPerformed

    private void picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picActionPerformed

        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(productinformation.this);

        if(result==JFileChooser.CANCEL_OPTION){
            chooser.disable();
            filename = null;
            Product_Image.setIcon(null);
        }

        else{
            File f = chooser.getSelectedFile();
            filename = f.getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(Product_Image.getWidth(), Product_Image.getHeight(), Image.SCALE_DEFAULT));
            Product_Image.setIcon(imageIcon);

            try {

                File image = new File(filename);
                img = new FileInputStream (image);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);

            }    }

    }//GEN-LAST:event_picActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Connection con = ModelLogin.getConnection();
//        String array[] = jComboBox1.getSelectedItem().toString();
//        for (int j = 0; j < jComboBox1.getSelectedItem().toString().length(); j++) {
//         String a = jComboBox1.getSelectedItem().toString()[j].indexOf('.');    
//        String b = jComboBox1.getSelectedItem().toString()[j].lastIndexOf('.');
//        String str = jComboBox1.getSelectedItem().toString()[j].substring(a+1, b);
//        }
 
        try {
            String s= jComboBox1.getSelectedItem().toString();
            String a[] = s.split(" ");
            
            ps=con.prepareStatement("SELECT * FROM product WHERE name = '"+a[0]+"'");
           // ps.setString(1,(String)jComboBox6.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            { 
             String q = rs.getString("unit");
             String d = rs.getString("quantity");
              byte [] img = rs.getBytes("image");
               
//               ImageIcon image = new ImageIcon(new ImageIcon(image.getImage()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
//              Image im = image.getImage();
//              Image myImage = im.getScaledInstance(Label_ImageP.getWidth(), Label_ImageP.getHeight(), Image.SCALE_SMOOTH);
//              ImageIcon newImage = new ImageIcon(myImage);
//                 Label_ImageP.setIcon(newImage);
//            
                 
               ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(Label_ImageP.getWidth(), Label_ImageP.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                Label_ImageP.setIcon(newImage);
             jTable1.setValueAt(d, i, 1);
             jTable1.setValueAt(q, i, 2);
             jTable1.setSelectionBackground(Color.GREEN);
//             jTable1.getColumn("PICTURE").setCellRenderer(new LabelRenderer());
//             jTable1.setValueAt(Label_ImageP, i, 3);
             i++;
            }}
            catch(Exception e){
//                System.out.println(""+e);
            }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Product_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Product_NameKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
       {
              evt.consume();
       }
    }//GEN-LAST:event_Product_NameKeyTyped

    private void UnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnitKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
       {
              evt.consume();
       }
    }//GEN-LAST:event_UnitKeyTyped

    private void QuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
       {
              evt.consume();
       }
    }//GEN-LAST:event_QuantityKeyTyped

    private void Characteristics_Type_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Characteristics_Type_NameKeyTyped
        if(Character.isDigit(evt.getKeyChar()))
       {
              evt.consume();
       }
    }//GEN-LAST:event_Characteristics_Type_NameKeyTyped

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
   
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productinformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productinformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Characteristics_Type_Name;
    private javax.swing.JTextField Characteristics_Value;
    private javax.swing.JLabel Label_ImageP;
    private javax.swing.JLabel Product_Image;
    private javax.swing.JTextField Product_Name;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton REPORT;
    private javax.swing.JTextField Unit;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pic;
    // End of variables declaration//GEN-END:variables
}
