package login;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vik
 */
public class Quotation extends javax.swing.JFrame {
    public Connection con;
    public PreparedStatement ps;
    ResultSet rs;
    
   Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Vik\\Desktop\\ISE FINAL PROJECT'\\Capture.PNG");
     
    /**
     * Creates new form TENDER
     */
    public Quotation() {
        initComponents();
        this.setIconImage(ic);
        this.setLocationRelativeTo(null);
        ModelLogin cl = new ModelLogin();
    ModelQuotation mq = new ModelQuotation();
    mq.statusComboQ(Client_Id);
     mq.statusComboQ1(LPR_Number);
     mq.statusComboQ2(desc);
  
    }
     private ImageIcon format =null;
    //strin filename
    String filename = null;
    byte[] person_image = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Client_Name = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Delivery = new javax.swing.JLabel();
        LPR_Number = new javax.swing.JComboBox<>();
        status = new javax.swing.JComboBox<>();
        Client_Id = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton21 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        IT_Confirmed = new javax.swing.JLabel();
        Client_Image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        Validity = new javax.swing.JLabel();
        Label_Description = new javax.swing.JLabel();
        Made = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Tender_Id = new javax.swing.JLabel();
        Reference_Number = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        NTN_Number = new javax.swing.JTextField();
        Pattern_Number = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desc = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(153, 153, 153));
        jButton12.setText("     ATTACH IMAGE");
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 10, 300, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("     ISSUE MATERIAL");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(60, 420, 160, 30);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 153, 153));
        jButton7.setText("     CLIENT ORDER");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 380, 160, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("     GENERATE BILL");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(60, 340, 160, 30);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 153, 153));
        jButton9.setText("     GET RATES");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(60, 300, 160, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 153, 153));
        jButton10.setText("       QUOTATION");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(60, 260, 160, 30);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 153, 153));
        jButton11.setText("     TENDER");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(60, 220, 160, 30);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(153, 153, 153));
        jButton13.setText("GENERATE PAYMENT");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(60, 500, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/deal (4).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 270, 180);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QOUTATION");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 60, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("     GENERATE QOUTATION");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 290, 760, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DATE");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(690, 360, 150, 20);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STATUS");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 360, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("REFERENCE NUMBER");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(690, 330, 150, 20);

        Client_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Client_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Name);
        Client_Name.setBounds(510, 160, 150, 20);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("LPR NUMBER");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel20);
        jLabel20.setBounds(340, 390, 150, 20);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 153, 153));
        jButton15.setText("PAY THE PAYMENT");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(60, 460, 160, 30);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("     QOUTATION LINE ITEM");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(310, 570, 760, 20);

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("     CLIENT INFORMATION");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 90, 760, 30);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ID");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(340, 130, 150, 20);

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("NAME");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(340, 160, 150, 20);

        Delivery.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Delivery.setForeground(new java.awt.Color(255, 255, 255));
        Delivery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delivery.setText("90 DAYS");
        Delivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Delivery);
        Delivery.setBounds(510, 480, 150, 20);

        LPR_Number.setBackground(new java.awt.Color(153, 153, 153));
        LPR_Number.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        LPR_Number.setForeground(new java.awt.Color(153, 153, 153));
        LPR_Number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        LPR_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LPR_Number.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LPR_Number.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        LPR_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPR_NumberActionPerformed(evt);
            }
        });
        jPanel1.add(LPR_Number);
        LPR_Number.setBounds(510, 390, 150, 22);

        status.setBackground(new java.awt.Color(153, 153, 153));
        status.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(153, 153, 153));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "status", "Complete", "Incomplete" }));
        status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        status.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        status.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status);
        status.setBounds(510, 360, 150, 22);

        Client_Id.setBackground(new java.awt.Color(153, 153, 153));
        Client_Id.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Id.setForeground(new java.awt.Color(153, 153, 153));
        Client_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        Client_Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Client_Id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Client_Id.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Client_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Id);
        Client_Id.setBounds(510, 130, 150, 22);

        jComboBox5.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox5.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(510, 130, 150, 22);

        jButton21.setBackground(new java.awt.Color(0, 0, 0));
        jButton21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(153, 153, 153));
        jButton21.setText("GENERATE REPORT");
        jButton21.setBorder(null);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(550, 540, 170, 20);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DESCRIPTION", "LPR NO", "QUANTITY ", "UNIT PRICE ", "TOTAL SUM"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(250);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(600);
            jTable1.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(desc));
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 600, 600, 100);

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("DELIEVERY");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(340, 480, 150, 20);

        jLabel31.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("IT CONFIRMED");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel31);
        jLabel31.setBounds(690, 420, 150, 20);

        Description.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Description);
        Description.setBounds(510, 510, 500, 20);

        IT_Confirmed.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        IT_Confirmed.setForeground(new java.awt.Color(255, 255, 255));
        IT_Confirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IT_Confirmed.setText("YES");
        IT_Confirmed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(IT_Confirmed);
        IT_Confirmed.setBounds(860, 420, 150, 20);

        Client_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Image);
        Client_Image.setBounds(800, 130, 160, 150);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1043, 10, 30, 23);

        jButton22.setBackground(new java.awt.Color(0, 0, 0));
        jButton22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(153, 153, 153));
        jButton22.setText("GENERATE QUOTATION");
        jButton22.setBorder(null);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(730, 540, 170, 20);

        Validity.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Validity.setForeground(new java.awt.Color(255, 255, 255));
        Validity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Validity.setText("30 DAYS");
        Validity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Validity);
        Validity.setBounds(860, 450, 150, 20);

        Label_Description.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Label_Description.setForeground(new java.awt.Color(255, 255, 255));
        Label_Description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Description.setText("DESCRIPTION");
        Label_Description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Label_Description);
        Label_Description.setBounds(340, 510, 150, 20);

        Made.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Made.setForeground(new java.awt.Color(255, 255, 255));
        Made.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Made.setText("LOCAL");
        Made.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Made);
        Made.setBounds(510, 450, 150, 20);

        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("MADE");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel37);
        jLabel37.setBounds(340, 450, 150, 20);

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("VALIDITY");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel27);
        jLabel27.setBounds(690, 450, 150, 20);

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("TENDER ID");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel29);
        jLabel29.setBounds(690, 390, 150, 20);

        Tender_Id.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Tender_Id.setForeground(new java.awt.Color(255, 255, 255));
        Tender_Id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tender_Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Tender_Id);
        Tender_Id.setBounds(860, 390, 150, 20);

        Reference_Number.setText("Enter Ref No");
        Reference_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Reference_Number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reference_NumberMouseClicked(evt);
            }
        });
        Reference_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reference_NumberActionPerformed(evt);
            }
        });
        Reference_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Reference_NumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Reference_NumberKeyTyped(evt);
            }
        });
        jPanel1.add(Reference_Number);
        Reference_Number.setBounds(860, 330, 150, 20);

        jLabel39.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("PATTERN NUMBER");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel39);
        jLabel39.setBounds(340, 420, 150, 20);

        jLabel40.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("NTN NUMBER");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel40);
        jLabel40.setBounds(340, 330, 150, 20);

        Date.setBackground(new java.awt.Color(204, 204, 204));
        Date.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Date.setOpaque(false);
        jPanel1.add(Date);
        Date.setBounds(860, 360, 150, 20);

        NTN_Number.setText("Enter NTN No");
        NTN_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NTN_Number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NTN_NumberMouseClicked(evt);
            }
        });
        NTN_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NTN_NumberActionPerformed(evt);
            }
        });
        NTN_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NTN_NumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NTN_NumberKeyTyped(evt);
            }
        });
        jPanel1.add(NTN_Number);
        NTN_Number.setBounds(510, 330, 150, 20);

        Pattern_Number.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Pattern_Number.setForeground(new java.awt.Color(255, 255, 255));
        Pattern_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pattern_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Pattern_Number);
        Pattern_Number.setBounds(510, 420, 150, 20);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(153, 153, 153));
        jButton18.setText("VENDOR INFORMATION");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(60, 580, 160, 30);

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(153, 153, 153));
        jButton19.setText("PRDOUCT INFORMATION");
        jButton19.setBorder(null);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(60, 620, 160, 30);

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        jButton20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(153, 153, 153));
        jButton20.setText("CLIENT INFORMATION");
        jButton20.setBorder(null);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(60, 540, 160, 30);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(153, 153, 153));
        jButton17.setText("SAVE");
        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(910, 540, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -60, 1080, 790);

        desc.setBackground(new java.awt.Color(153, 153, 153));
        desc.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 153, 153));
        desc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        desc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desc.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        jPanel1.add(desc);
        desc.setBounds(510, 360, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         GENERATEBILLform gb = new GENERATEBILLform();
        gb.setVisible(true);
        gb.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         Quotation q = new Quotation();
        q.setVisible(true);
        q.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void LPR_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPR_NumberActionPerformed
        // TODO add your handling code here:
     Connection con = ModelLogin.getConnection();
        try {
            ps = con.prepareStatement("SELECT tid,nsnno,description FROM tender WHERE `lprno` =?");
            ps.setString(1, (String) LPR_Number.getSelectedItem());
            rs = ps.executeQuery();
            while (rs.next()) {
                Tender_Id.setText(rs.getString("tid"));
                Pattern_Number.setText(rs.getString("nsnno"));
              Description.setText(rs.getString("description"));
//                String st = status.getSelectedItem().toString();
//                ps.setString(3, st);
            }
        } catch (Exception e) {
        }              
        
    }//GEN-LAST:event_LPR_NumberActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void Client_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_IdActionPerformed
        // TODO add your handling code here:
         Connection con = ModelLogin.getConnection();
         
        try {
             ps=con.prepareStatement("SELECT `name`,image FROM `client` WHERE `clientid` =?");
             ps.setString(1,(String)Client_Id.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            {
                Client_Name.setText(rs.getString("name"));
                   byte [] img = rs.getBytes("image");
               ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(Client_Image.getWidth(), Client_Image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                Client_Image.setIcon(newImage);
          
                
     

        }
        }
        catch(Exception e){
                
                }
        
    }//GEN-LAST:event_Client_IdActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     dispose();
     hp.setLocationRelativeTo(null);
setVisible(false);
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
          
        if (Client_Id.getSelectedItem().toString().equals("") || Client_Name.getText().equals("") || 
         Tender_Id.getText().equals("") || NTN_Number.getText().equals("") || Reference_Number.getText().equals("") || 
       status.getSelectedItem().toString().equals("") || LPR_Number.getSelectedItem().toString().equals("") || Pattern_Number.getText().equals("") || 
        Date.getDate().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields");
        }
        else
        {
          Connection con = ModelLogin.getConnection();
          String ntn = Reference_Number.getText();
          String ref = Reference_Number.getText();
          Made.getText();
          Delivery.getText();
          Description.getText();
          IT_Confirmed.getText();
          
          
                 java.util.Date date=Date.getDate();
                java.sql.Date sqlDate=new java.sql.Date(date.getTime()); 
                try {
             ps=con.prepareStatement("INSERT INTO `generate_quotation`(`tid`, `date`, `status`, `referenceno`, `patternno`, `ntnno`, `delivery`,`description`, `validity`, `lprno`, `itconfirmed`, `clientid`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
             ps.setString(1, Tender_Id.getText());
             ps.setDate(2,sqlDate);
             ps.setString(3,status.getSelectedItem().toString());
             ps.setString(4, ref);
             ps.setString(5,Pattern_Number.getText() );
             ps.setString(6, ntn);
              ps.setString(7, Delivery.getText());
              ps.setString(8, Description.getText());
              ps.setString(9, Validity.getText());
              ps.setString(10, LPR_Number.getSelectedItem().toString());
              ps.setString(11, IT_Confirmed.getText());
              ps.setString(12, Client_Id.getSelectedItem().toString());
             ps.execute();
            JOptionPane.showMessageDialog(this, "values addeed successfully ");
             Reference_Number.setText("");
             Pattern_Number.setText("");
             Client_Id.setSelectedIndex(0);
             Client_Name.setText("");
             Client_Image.setIcon(null);
             status.setSelectedIndex(0);
             LPR_Number.setSelectedIndex(0);
             NTN_Number.setText("");
             Date.setDate(null);
             Tender_Id.setText("");
             Description.setText("");
                } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "nilll values addeed successfully "+ex);
                    System.out.println(ex);
        }
        }
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void Reference_NumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reference_NumberMouseClicked
        // TODO add your handling code here:
        Reference_Number.setText(null);

    }//GEN-LAST:event_Reference_NumberMouseClicked

    private void Reference_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reference_NumberActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_Reference_NumberActionPerformed

    private void Reference_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Reference_NumberKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Reference_NumberKeyPressed

    private void Reference_NumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Reference_NumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Reference_NumberKeyTyped

    private void NTN_NumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NTN_NumberMouseClicked
        // TODO add your handling code here:
        NTN_Number.setText(null);
    }//GEN-LAST:event_NTN_NumberMouseClicked

    private void NTN_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NTN_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NTN_NumberActionPerformed

    private void NTN_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NTN_NumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NTN_NumberKeyPressed

    private void NTN_NumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NTN_NumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NTN_NumberKeyTyped

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     hp.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        TENDER t = new TENDER();
t.setVisible(true);
t.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        GETRATES gr = new GETRATES();
        gr.setVisible(true);
        gr.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CLIENTORDER co = new CLIENTORDER();
        co.setVisible(true);
        co.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ISSUEMATERIAL im = new ISSUEMATERIAL();
        im.setVisible(true);
        im.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         VENDERINFORMATION vm = new VENDERINFORMATION();
        vm.setVisible(true);
        vm.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        ClientInformation ci = new ClientInformation();
        ci.setVisible(true);
        ci.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        generateQuotation pi = new generateQuotation();
        pi.setVisible(true);
        pi.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    }//GEN-LAST:event_jButton13ActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
Connection con = ModelLogin.getConnection();
        int i =0;
        double tprice;
        try {
            ps=con.prepareStatement("SELECT * FROM get_rates WHERE description = '"+desc.getSelectedItem()+"'");
           // ps.setString(1,(String)jComboBox6.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
 
            {
             String lpr=rs.getString("lprnno");
             int q = rs.getInt("quantity");
             int d = rs.getInt("price");
                      tprice= d*q;
            
             System.out.println(q);
             jTable1.setValueAt(lpr, i, 1);
             jTable1.setValueAt(q, i, 2);
             jTable1.setValueAt(d, i, 3);
             jTable1.setValueAt(tprice, i, 4);

             i++;            }}
            catch(Exception e){

            }
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        
               Connection con = ModelLogin.getConnection();
        try {
           String path="E:\\FISE PROJECT\\Tender Managment System Final\\LOGIN\\src\\login\\Quotation.jrxml";
           JasperReport jr = JasperCompileManager.compileReport(path);
           JasperPrint jp =JasperFillManager.fillReport(jr, null, con);
           JasperViewer.viewReport(jp,false);
           con.close();
       } catch (JRException ex) {
           Logger.getLogger(Quotation.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {        
            Logger.getLogger(CLIENTVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
     
//       XWPFDocument document = new XWPFDocument();
//       XWPFParagraph paragraph = document.createParagraph();
//       XWPFRun run =paragraph.createRun();
//       run.addBreak();
//       run.addBreak();
//       run.setText("Ref No: "+Reference_Number.getText());
//       run.addBreak();
//       run.setText("STN # 3277876131686"+"                                                                                                                    NTN # 7332121-1");
//       run.addBreak();
//       run.setText("                                                                     QUOTATION FOR LRP");
//       run.addBreak();
//       run.setText("                                                            LPR No: "+LPR_Number.getSelectedItem().toString()+"          Dated: "+Date.getDate().toString());
//       run.addBreak();
//       run.setText("1. NSN/Pattern No                                                                                          : "+Pattern_Number.getText());
//       run.addBreak();
//       run.setText("2. Description                                                                                          : " +Description.getText());
//       run.addBreak();
//       run.setText("3. Made                                                                                 : " +Made.getText());
//       run.addBreak();
//       run.setText("4. Unit Price With GST                                                         : " +Description.getText());
//       run.addBreak();
//       run.setText("5. Quantity                                                                            : " +Description.getText());
//       run.addBreak();
//       run.setText("6. Demination            			                   : " +Description.getText());
//       run.addBreak();
//       run.setText("7. Delivery                                                                             : " +Description.getText());
//       run.addBreak();
//       run.setText("8. Validity                                                                              : " +Description.getText());
//       run.addBreak();
//       run.setText("9. IT Confirmed                                                                    : " +Description.getText());
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.addBreak();
//       run.setText("                                                                                                                                      Best Regards                ");
//       run.addBreak();
//       run.addBreak();
//       run.setText("                                                                                                                                      A.D & COMPANY                ");
//       try {
//            FileOutputStream output = new FileOutputStream("C:\\Users\\apex\\Desktop\\Awesome.docx");
//            document.write(output);
//            output.close();
//            JOptionPane.showMessageDialog(null, "Quotation generated successfully.....");
//        } catch (Exception e) {
//            System.out.println(e);
//        } 
        
        
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
   
        generateQuotation gq = new generateQuotation();
        gq.setVisible(true);
        gq.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quotation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quotation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Client_Id;
    private javax.swing.JLabel Client_Image;
    private javax.swing.JLabel Client_Name;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JLabel Delivery;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel IT_Confirmed;
    private javax.swing.JComboBox<String> LPR_Number;
    private javax.swing.JLabel Label_Description;
    private javax.swing.JLabel Made;
    private javax.swing.JTextField NTN_Number;
    private javax.swing.JLabel Pattern_Number;
    private javax.swing.JTextField Reference_Number;
    private javax.swing.JLabel Tender_Id;
    private javax.swing.JLabel Validity;
    private javax.swing.JComboBox<String> desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
