package login;



import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vik
 */
public class TENDER extends javax.swing.JFrame {

   
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
   Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Vik\\Desktop\\ISE FINAL PROJECT'\\Capture.PNG");
     
    /**
     * Creates new form TENDER
     */
    public TENDER() {
        initComponents();
    
         ModelLogin ml = new ModelLogin();
         Model m = new Model();
         m.statusCombo(Client_Id);
       
         m.statusCombo2(jComboBox6);
    
       
       this.setIconImage(ic);
       this.setLocationRelativeTo(null);
      
        jTable2.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBox6));
       }
     private ImageIcon format =null;
     
    //strin filename
    String filename = null;
    byte[] person_image = null;
   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Client_Name = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LPR_Number = new javax.swing.JTextField();
        Part_Number = new javax.swing.JTextField();
        NSN_Number = new javax.swing.JTextField();
        Description = new javax.swing.JTextField();
        Quantity = new javax.swing.JTextField();
        Deno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        Client_Id = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        Client_Image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(153, 153, 153));
        jButton12.setText("     ATTACH IMAGE");
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 10, 300, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("     ISSUE MATERIAL");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(60, 420, 160, 30);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(153, 153, 153));
        jButton7.setText("     CLIENT ORDER");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(60, 380, 160, 30);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 153, 153));
        jButton8.setText("     GENERATE BILL");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(60, 340, 160, 30);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(153, 153, 153));
        jButton9.setText("     GET RATES");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(60, 300, 160, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 153, 153));
        jButton10.setText("       QOUTATION");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(60, 260, 160, 30);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(153, 153, 153));
        jButton11.setText("     TENDER");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(60, 220, 160, 30);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(153, 153, 153));
        jButton13.setText("GENERATE PAYMENT");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(60, 500, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/deal (4).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 270, 180);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Description", "Quantity", "Unit"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 602, 590, 110);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TENDER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 60, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("     TENDER");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 320, 760, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("QUANTITY");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 420, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DESCRIPTION");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 450, 150, 20);

        Client_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Name.setForeground(new java.awt.Color(255, 255, 255));
        Client_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Client_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Name);
        Client_Name.setBounds(510, 160, 150, 20);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 153, 153));
        jButton15.setText("PAY THE PAYMENT");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(60, 460, 160, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1040, 0, 40, 40);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("     TENDER DETAILS");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(310, 540, 760, 30);

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("     CLIENT INFORMATION");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 90, 760, 30);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ID");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(340, 130, 150, 20);

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("NSN NUMBER");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(690, 390, 150, 20);

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("NAME");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(340, 160, 150, 20);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("DENO");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(690, 420, 150, 20);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATE");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(690, 360, 150, 20);

        LPR_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        LPR_Number.setOpaque(false);
        LPR_Number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LPR_NumberMouseClicked(evt);
            }
        });
        LPR_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPR_NumberActionPerformed(evt);
            }
        });
        LPR_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LPR_NumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LPR_NumberKeyTyped(evt);
            }
        });
        jPanel1.add(LPR_Number);
        LPR_Number.setBounds(510, 360, 150, 20);

        Part_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Part_Number.setOpaque(false);
        Part_Number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Part_NumberMouseClicked(evt);
            }
        });
        Part_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part_NumberActionPerformed(evt);
            }
        });
        Part_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Part_NumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Part_NumberKeyTyped(evt);
            }
        });
        jPanel1.add(Part_Number);
        Part_Number.setBounds(510, 390, 150, 20);

        NSN_Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NSN_Number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NSN_NumberMouseClicked(evt);
            }
        });
        NSN_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSN_NumberActionPerformed(evt);
            }
        });
        NSN_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NSN_NumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NSN_NumberKeyTyped(evt);
            }
        });
        jPanel1.add(NSN_Number);
        NSN_Number.setBounds(860, 390, 150, 20);

        Description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Description.setOpaque(false);
        Description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DescriptionMouseClicked(evt);
            }
        });
        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });
        Description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DescriptionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DescriptionKeyTyped(evt);
            }
        });
        jPanel1.add(Description);
        Description.setBounds(510, 450, 500, 20);

        Quantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Quantity.setOpaque(false);
        Quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuantityMouseClicked(evt);
            }
        });
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        Quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantityKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityKeyTyped(evt);
            }
        });
        jPanel1.add(Quantity);
        Quantity.setBounds(510, 420, 150, 20);

        Deno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Deno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DenoMouseClicked(evt);
            }
        });
        Deno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenoActionPerformed(evt);
            }
        });
        Deno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DenoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DenoKeyTyped(evt);
            }
        });
        jPanel1.add(Deno);
        Deno.setBounds(860, 420, 150, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2);
        jButton2.setBounds(1330, 0, 40, 40);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(153, 153, 153));
        jButton16.setText("REPORT ");
        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(730, 480, 130, 20);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("LPR NUMBER");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(340, 360, 150, 20);

        Date.setBackground(new java.awt.Color(153, 153, 153));
        Date.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Date.setOpaque(false);
        jPanel1.add(Date);
        Date.setBounds(860, 360, 150, 20);

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("PART NO");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(340, 390, 150, 20);

        Client_Id.setBackground(new java.awt.Color(153, 153, 153));
        Client_Id.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Client_Id.setForeground(new java.awt.Color(153, 153, 153));
        Client_Id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Client_Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Client_Id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Client_Id.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Client_Id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Client_IdFocusLost(evt);
            }
        });
        Client_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Client_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Client_Id);
        Client_Id.setBounds(510, 130, 150, 22);

        jComboBox5.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox5.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(510, 130, 150, 22);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(153, 153, 153));
        jButton14.setText("SAVE");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(880, 480, 130, 20);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(153, 153, 153));
        jButton18.setText("VENDOR INFORMATION");
        jButton18.setBorder(null);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(60, 580, 160, 30);

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(153, 153, 153));
        jButton19.setText("PRDOUCT INFORMATION");
        jButton19.setBorder(null);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(60, 620, 160, 30);

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        jButton20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(153, 153, 153));
        jButton20.setText("CLIENT INFORMATION");
        jButton20.setBorder(null);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(60, 540, 160, 30);

        Client_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(Client_Image);
        Client_Image.setBounds(780, 130, 170, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -60, 1080, 890);

        jComboBox6.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox6.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(510, 380, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         GENERATEBILLform gb = new GENERATEBILLform();
        gb.setVisible(true);
        gb.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         Quotation q = new Quotation();
        q.setVisible(true);
        q.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Client_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Client_IdActionPerformed

          Connection con = ModelLogin.getConnection();
         
        try {
             ps=con.prepareStatement("SELECT `name`,image FROM `client` WHERE `clientid` =?");
             ps.setString(1,(String)Client_Id.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            {
                Client_Name.setText(rs.getString("name"));
                   byte [] img = rs.getBytes("image");
               ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image myImage = im.getScaledInstance(Client_Image.getWidth(), Client_Image.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImage);
                Client_Image.setIcon(newImage);
          
                
     

        }}
        catch(Exception e){
                
                }
        
        
    
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_IdActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
       if (Client_Id.getSelectedItem().toString().equals("") || Client_Name.getText().equals("") || 
         LPR_Number.getText().equals("") || NSN_Number.getText().equals("") || Quantity.getText().equals("") || 
       Part_Number.getText().equals("") || Description.getText().equals("") || Deno.getText().equals("") || 
        Date.getDate().toString().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields");
        }
        else
        { 
        Connection con = ModelLogin.getConnection();
        
             String lpr = LPR_Number.getText();
             String partno = Part_Number.getText();
             String nsn = NSN_Number.getText();
             String desc =  Description.getText();
             String quantity = Quantity.getText();
             String deno = Deno.getText();
             java.util.Date date=Date.getDate();
                java.sql.Date Dat=new java.sql.Date(date.getTime());
        try {
             ps=con.prepareStatement("INSERT INTO `tender`(`lprno`, `partno`, `nsnno`, `description`, `quantity`, `deno`, `date`, `clientid`) VALUES (?,?,?,?,?,?,?,?)");
                        Statement st = con.createStatement();

             ps.setString(1, lpr);
             ps.setString(2, partno);
             ps.setString(3, nsn);
             ps.setString(4, desc);
             ps.setString(5, quantity);
             ps.setString(6, deno);
              ps.setDate(7,Dat);
              ps.setString(8, Client_Id.getSelectedItem().toString());
             ps.execute();
            JOptionPane.showMessageDialog(this, "values addeed successfully ");
             Client_Id.setSelectedIndex(0);
             Client_Name.setText("");
             Client_Image.setIcon(null);
             LPR_Number.setText("");
             Part_Number.setText("");
             NSN_Number.setText("");
             Description.setText("");
             Quantity.setText("");
             Deno.setText("");
             Date.setDate(null);
             
        } catch (Exception e) {
        }
           
           
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        Connection con = ModelLogin.getConnection();
        int i =0;
        try {
            ps=con.prepareStatement("SELECT * FROM tender WHERE description = '"+jComboBox6.getSelectedItem()+"'");
           // ps.setString(1,(String)jComboBox6.getSelectedItem());
            rs=ps.executeQuery();
            while(rs.next())
            {
             String q = rs.getString("quantity");
             String d = rs.getString("deno");   
             System.out.println(q);
             jTable2.setValueAt(q, i, 1);
             jTable2.setValueAt(d, i, 2);
             i++;
            }}
            catch(Exception e){

            }
    }//GEN-LAST:event_jComboBox6ActionPerformed
    
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     dispose();
     hp.setLocationRelativeTo(null);
setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void LPR_NumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LPR_NumberMouseClicked
     
        // TODO add your handling code here:
    }//GEN-LAST:event_LPR_NumberMouseClicked

    private void LPR_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPR_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LPR_NumberActionPerformed

    private void LPR_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LPR_NumberKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_LPR_NumberKeyPressed

    private void LPR_NumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LPR_NumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LPR_NumberKeyTyped

    private void Part_NumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part_NumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Part_NumberMouseClicked

    private void Part_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Part_NumberActionPerformed

    private void Part_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Part_NumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Part_NumberKeyPressed

    private void Part_NumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Part_NumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Part_NumberKeyTyped

    private void NSN_NumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NSN_NumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NSN_NumberMouseClicked

    private void NSN_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NSN_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NSN_NumberActionPerformed

    private void NSN_NumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSN_NumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NSN_NumberKeyPressed

    private void NSN_NumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NSN_NumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NSN_NumberKeyTyped

    private void DescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescriptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionMouseClicked

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed

    private void DescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescriptionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionKeyPressed

    private void DescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescriptionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionKeyTyped

    private void QuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityMouseClicked

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void QuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityKeyPressed

    private void QuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityKeyTyped

    private void DenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DenoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DenoMouseClicked

    private void DenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DenoActionPerformed

    private void DenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DenoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DenoKeyPressed

    private void DenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DenoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DenoKeyTyped

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     hp.setLocationRelativeTo(null);
     setVisible(false);        

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        TENDER t = new TENDER();
t.setVisible(true);
t.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        GETRATES gr = new GETRATES();
        gr.setVisible(true);
        gr.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        CLIENTORDER co = new CLIENTORDER();
        co.setVisible(true);
        co.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         ISSUEMATERIAL im = new ISSUEMATERIAL();
        im.setVisible(true);
        im.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         VENDERINFORMATION vm = new VENDERINFORMATION();
        vm.setVisible(true);
        vm.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
       generateQuotation pi = new generateQuotation();
        pi.setVisible(true);
        pi.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       ClientInformation ci = new ClientInformation();
        ci.setVisible(true);
        ci.setLocationRelativeTo(null);
setVisible(false);        

    }//GEN-LAST:event_jButton20ActionPerformed

    private void Client_IdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Client_IdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Client_IdFocusLost

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                Connection con = ModelLogin.getConnection();
        try {
           String path="E:\\FISE PROJECT\\Tender Managment System Final\\LOGIN\\src\\login\\Tendors.jrxml";
           JasperReport jr = JasperCompileManager.compileReport(path);
           JasperPrint jp =JasperFillManager.fillReport(jr, null, con);
           JasperViewer.viewReport(jp,false);
           con.close();
       } catch (JRException ex) {
           Logger.getLogger(Quotation.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {        
            Logger.getLogger(CLIENTVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
    }//GEN-LAST:event_jButton16ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TENDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TENDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TENDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TENDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TENDER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Client_Id;
    private javax.swing.JLabel Client_Image;
    private javax.swing.JLabel Client_Name;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTextField Deno;
    private javax.swing.JTextField Description;
    private javax.swing.JTextField LPR_Number;
    private javax.swing.JTextField NSN_Number;
    private javax.swing.JTextField Part_Number;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
