package login;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/** 
 *
 * @author Vik
 */
public class VENDERINFORMATION extends javax.swing.JFrame {
Connection con;
    PreparedStatement ps;
    ResultSet rs;
    String filename = null;
    Image ic = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Vik\\Desktop\\ISE FINAL PROJECT'\\Capture.PNG");
    InputStream img;
    byte[] person_image = null;
    String imgpath=null;
    
    public VENDERINFORMATION() {
        initComponents();
        ModelLogin ml = new ModelLogin();
        this.setIconImage(ic);
        this.setLocationRelativeTo(null);
        
    }
public ImageIcon ResizeImage(String ImagePath,byte[] pic)
     {
       ImageIcon Myimage=null;
       if(ImagePath != null)
       {
           Myimage = new ImageIcon(ImagePath);
       }
       else
       {
           Myimage = new ImageIcon(pic);
       }
       Image img = Myimage.getImage();
       Image newImg = img.getScaledInstance(Vendor_Image.getWidth(),Vendor_Image.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon image = new ImageIcon(newImg);
       return image;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pic = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Vendor_Name = new javax.swing.JTextField();
        Vendor_Contact = new javax.swing.JTextField();
        Vendor_Address = new javax.swing.JTextField();
        Vendor_Image = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Vcontact = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A.D & COMPANY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 0, 300, 70);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VENDOR INFORMATION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 40, 250, 50);

        pic.setBackground(new java.awt.Color(102, 102, 102));
        pic.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        pic.setText("ATTACH IMAGE");
        pic.setBorder(null);
        pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picActionPerformed(evt);
            }
        });
        jPanel1.add(pic);
        pic.setBounds(210, 310, 220, 20);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("VIEW");
        jButton2.setActionCommand("");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 500, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADDRESS");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 430, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("NAME");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 350, 150, 20);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CONTACT");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 390, 150, 20);

        Vendor_Name.setBackground(new java.awt.Color(51, 51, 51));
        Vendor_Name.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Vendor_Name.setForeground(new java.awt.Color(255, 255, 255));
        Vendor_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vendor_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Vendor_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendor_NameActionPerformed(evt);
            }
        });
        jPanel1.add(Vendor_Name);
        Vendor_Name.setBounds(210, 350, 380, 20);

        Vendor_Contact.setBackground(new java.awt.Color(51, 51, 51));
        Vendor_Contact.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Vendor_Contact.setForeground(new java.awt.Color(255, 255, 255));
        Vendor_Contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vendor_Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Vendor_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendor_ContactActionPerformed(evt);
            }
        });
        jPanel1.add(Vendor_Contact);
        Vendor_Contact.setBounds(210, 390, 380, 20);

        Vendor_Address.setBackground(new java.awt.Color(51, 51, 51));
        Vendor_Address.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        Vendor_Address.setForeground(new java.awt.Color(255, 255, 255));
        Vendor_Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vendor_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Vendor_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendor_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Vendor_Address);
        Vendor_Address.setBounds(210, 430, 380, 20);

        Vendor_Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(Vendor_Image);
        Vendor_Image.setBounds(210, 90, 220, 210);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close-cross-circular-interface-button (2).png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(580, 0, 30, 30);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton4.setText("SAVE");
        jButton4.setActionCommand("");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(390, 500, 150, 20);

        Vcontact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/black_background_lines_scratches_69440_1366x768.jpg"))); // NOI18N
        jPanel1.add(Vcontact);
        Vcontact.setBounds(0, 0, 620, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picActionPerformed
         JFileChooser chooser = new JFileChooser();
//        chooser.setCurrentDirectory(new File(System.getProperty("User.home")));
        int result = chooser.showOpenDialog(null);
        
         if(result==JFileChooser.CANCEL_OPTION){
                    chooser.disable();
                    JOptionPane.showMessageDialog(null, "No Image Selected");
           filename = null;
                    Vendor_Image.setIcon(null);
                    
         }
         
         else{
         File f = chooser.getSelectedFile();
         String sf = f.getAbsolutePath();
         Vendor_Image.setIcon((ResizeImage(sf,null)));
//        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(CImage.getWidth(), CImage.getHeight(), Image.SCALE_DEFAULT));
//        CImage.setIcon(imageIcon);
//        
        imgpath = sf; 

      
                                  
      try {

            File image = new File(filename);
             FileInputStream fis = new FileInputStream (image);
        }
        catch(Exception e){
            
       
        }
         }

    }//GEN-LAST:event_picActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VENDORVIEW vv = new VENDORVIEW();
        vv.setVisible(true);
        vv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Vendor_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendor_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vendor_ContactActionPerformed

    private void Vendor_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendor_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vendor_AddressActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        HOMEPAGE hp = new HOMEPAGE();
     hp.setVisible(true);
     dispose();
     hp.setLocationRelativeTo(null);
setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            if(Vendor_Contact.getText().equals("") || Vendor_Address.getText().equals("") || Vendor_Name.getText().equals("") 
           || Vendor_Image.getIcon().equals(null))
        {
           JOptionPane.showMessageDialog(null, "Please Fill All The Details");
           
        }
               else
            {
        String Name = Vendor_Name.getText();
        String Contact = Vendor_Contact.getText();
        String Address = Vendor_Address.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/database","root","");
            ps=(PreparedStatement)con.prepareStatement("INSERT INTO `vendor`(`name`, `startdate`, `enddate`, `contact`, `address`, `balance`, `status`, `image`) VALUES (?,?,?,?,?,?,?,?)");
           if(imgpath != null){ 
            img = new FileInputStream(new File(imgpath));
            }
            ps.setString(1, Name);
            ps.setString(2, null);
            ps.setString(3, null);
            ps.setString(4, Contact);
            ps.setString(5, Address);
            ps.setString(6, null);
            ps.setString(7, null);
            System.out.println(""+imgpath);
            ps.setBlob(8, img);
            ps.execute();
            JOptionPane.showMessageDialog(this, "DATA SAVED");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "EXCEPTION OCCUR");
             }}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Vendor_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendor_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vendor_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENDERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENDERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENDERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENDERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENDERINFORMATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vcontact;
    private javax.swing.JTextField Vendor_Address;
    private javax.swing.JTextField Vendor_Contact;
    private javax.swing.JLabel Vendor_Image;
    private javax.swing.JTextField Vendor_Name;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pic;
    // End of variables declaration//GEN-END:variables
}
